---
# install mysql-server

- name: install mysql
  apt: pkg=mysql-server state=latest
  notify:
    - start mysql-server

- name: install python-mysqldb
  apt: pkg=python-mysqldb state=installed

- name: open remote connections
  ini_file: dest=/etc/mysql/my.cnf option=bind_ip value= backup=yes

#- name: update mysql root password for all root accounts
#  mysql_user: name=root password=1234 priv=*.*:ALL

#- name: copy .my.cnf file with root password credentials
#  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0644
#  notify:
#    - start mysql-server