---
# install composer

- name: Ensure curl is installed (Debian).
  apt: pkg=curl state=installed
  when: ansible_os_family == 'Debian'

- name: Install Composer into the current directory.
  shell: >
    curl -sS https://getcomposer.org/installer | php
    creates={{ composer_path }}

- name: Move Composer into globally-accessible location.
  shell: >
    mv composer.phar {{ composer_path }}
    creates={{ composer_path }}

- name: Update Composer to latest version (if configured).
  shell: >
    php {{ composer_path }} self-update
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"
  when: composer_keep_updated

#- name: ???
#  shell: >
#    {{ composer_path }} config -g github-oauth.github.com f0a71c9745759dd6ca7b4dc45355d5d407dc9667